---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lixiaohua.
--- DateTime: 2021/7/16 10:39
---

local DungeonGameModeBase = Class()

function DungeonGameModeBase:OnReceiveBeginPlayEnd()
end

function DungeonGameModeBase:ReceiveBeginPlay()
    printf("DungeonGameModeBase:ReceiveBeginPlay")

    local DungeonActor = self:GetDungeonActor()
    if (IsValid(DungeonActor)) then
        DungeonActor.Config.Seed = self:GetRandomSeed()

        local LevelStreamingModel = DungeonActor.LevelStreamingModel;
        LevelStreamingModel.StartRoomId = self:GetStartRoomId()
        
        -- 记录door trigger
        self.tbDoorTrigger = {}

        printf("DungeonGameModeBase:ReceiveBeginPlay Seed:%d StartRoomId:%d", DungeonActor.Config.Seed, LevelStreamingModel.StartRoomId)
        DungeonActor:BuildDungeon()

        -- 当初始化完成时    
        LevelStreamingModel.OnInitialChunksLoaded:Add(self, self.OnDungeonChunksLoaded)

        -- 当有Chunk显示出来时
        LevelStreamingModel.OnChunkVisible:Add(self, self.EventOnChunkVisible)

        -- 当有Chunk卸载时
        LevelStreamingModel.OnChunkUnload:Add(self, self.EventOnChunkUnload);

        -- 当到达新过道时
        LevelStreamingModel.OnNewCorridor:Add(self, self.EventOnNewCorridor)
        
        printf("DungeonGameModeBase:ReceiveBeginPlay Bind Delegate")
    end
    self:OnReceiveBeginPlayEnd()
end

--- 得到起始房间
function DungeonGameModeBase:GetStartRoomId()
    return 0;
end

--- 当一个chunk块显示出来时
function DungeonGameModeBase:EventOnChunkVisible(Dungeon, DungeonStreamingChunk)
    print("OnChunkVisible", Dungeon, DungeonStreamingChunk);
end

--- 当到达新过道时
function DungeonGameModeBase:EventOnNewCorridor(CorridorId)
    print("EventOnNewCorridor ", CorridorId)
end

--- 当有Chunk卸载时
function DungeonGameModeBase:EventOnChunkUnload(Dungeon, DungeonStreamingChunk)
    print("EventOnChunkUnload", Dungeon, DungeonStreamingChunk);
end

function DungeonGameModeBase:GetRandomSeed()
    return UE4.UKismetMathLibrary.RandomInteger(100000)
end

function DungeonGameModeBase:OnDungeonChunksLoaded(Dungeon)
    printf("DungeonGameModeBase:OnDungeonChunksLoaded")

    self.bShouldStartMatch = true
end

function DungeonGameModeBase:GetDungeonActor()
    if (IsValid(self.DungeonActor)) then
        return self.DungeonActor
    end

    local DungeonActorArray = UE4.UGameplayStatics.GetAllActorsOfClass(self, UE4.ADungeon)
    if (DungeonActorArray:Length() <= 0) then
        printf_e("DungeonGameModeBase:GetDungeonActor Failed to find DungeonActor!")
        return
    end

    self.DungeonActor = DungeonActorArray:Get(1)

    return self.DungeonActor
end

function DungeonGameModeBase:GetGameTaskActor()
    if (IsValid(self.GameTaskActor)) then
        return self.GameTaskActor
    end

    local GameTaskActorArray = UE4.UGameplayStatics.GetAllActorsOfClass(self, UE4.AGameTaskActor)
    if (GameTaskActorArray:Length() <= 0) then
        printf_e("DungeonGameModeBase:GetGameTaskActor Failed to find GameTaskActor")
        return
    end

    self.GameTaskActor = GameTaskActorArray:Get(1)

    return self.GameTaskActor
end

function DungeonGameModeBase:ReceiveEndPlay()
    printf("DungeonGameModeBase:ReceiveEndPlay")

    self.GameTaskActor = nil
    self.DungeonActor = nil
    self.tbDoorTrigger = nil
end

return DungeonGameModeBase