---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lixiaohua.
--- DateTime: 2023/3/14 15:47
---

local MultiLevel = Class()

function MultiLevel:LoadStreamLevel(StreamingLevel, bMakeVisibleAfterLoad, bShouldBlockOnLoad)
    printf("MultiLevel:ReceiveBeginPlay LoadStreamLevel_Inner:%s", StreamingLevel)
    UE4.UGameplayStatics.LoadStreamLevel(GGameInstance, StreamingLevel, bMakeVisibleAfterLoad, bShouldBlockOnLoad)
end

function MultiLevel:ReceiveBeginPlay()
    printf("MultiLevel:ReceiveBeginPlay")

    if UE4.UKismetSystemLibrary.IsDedicatedServer(GGameInstance) then
       return
    end

    for i=1, self.ClientStreamingLevels:Num() do
        local StreamingLevel = self.ClientStreamingLevels:Get(i)
        coroutine.resume(coroutine.create(self.LoadStreamLevel), self, StreamingLevel, true, false)
        printf("MultiLevel:ReceiveBeginPlay LoadStreamLevel:%s", StreamingLevel)
    end
end

return MultiLevel
